// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiemensS7Demo.Persistence;

#nullable disable

namespace SiemensS7Demo.Persistence.Migrations
{
    [DbContext(typeof(EnviroDbContext))]
    partial class EnviroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SiemensS7Demo.Persistence.Entities.AlarmEventRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Muted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Reset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "At")
                        .HasDatabaseName("IX_AlarmEvents_DeviceId_At");

                    b.ToTable("AlarmEvents", (string)null);
                });

            modelBuilder.Entity("SiemensS7Demo.Persistence.Entities.HistoryPointRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Humid")
                        .HasColumnType("REAL");

                    b.Property<double?>("HumidSv")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pv")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sv")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "At")
                        .HasDatabaseName("IX_HistoryPoints_DeviceId_At");

                    b.ToTable("HistoryPoints", (string)null);
                });

            modelBuilder.Entity("SiemensS7Demo.Persistence.Entities.ProgramRow", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("SiemensS7Demo.Persistence.Entities.UserRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
